<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
	xmlns:simpleWebService="http://www.nicolas.com.ar/simpleWebService/"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns:types="http://www.nicolas.com.ar/simpleWebService/simpleWebServiceTypes"
	name="simpleWebService"
	targetNamespace="http://www.nicolas.com.ar/simpleWebService/">
	<wsdl:types>
		<xsd:schema>
			<xsd:import
				namespace="http://www.nicolas.com.ar/simpleWebService/simpleWebServiceTypes"
				schemaLocation="xsd/simpleWebServiceTypes.xsd" />
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="SimpleOperationRequest">
		<wsdl:part element="types:SimpleOperationRequest"
			name="simpleOperationRequest" />
	</wsdl:message>
	<wsdl:message name="SimpleOperationResponse">
		<wsdl:part element="types:SimpleOperationResponse"
			name="simpleOperationResponse" />
	</wsdl:message>
	<wsdl:message name="SimpleOperationFault">
		<wsdl:part element="types:SimpleOperationFault"
			name="simpleOperationFault" />
	</wsdl:message>
	<wsdl:portType name="simpleService">
		<wsdl:operation name="SimpleOperation">
			<wsdl:input name="simpleOpertionRequest"
				message="simpleWebService:SimpleOperationRequest" />
			<wsdl:output name="simpleOperationResponse"
				message="simpleWebService:SimpleOperationResponse" />
			<wsdl:fault name="simpleOperationFault" 
				message="simpleWebService:SimpleOperationFault" />
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="simpleServiceSOAP"
		type="simpleWebService:simpleService">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		<wsdl:operation name="SimpleOperation">
			<soap:operation
				soapAction="http://www.nicolas.com.ar/simpleWebService/simpleOperation" />
			<wsdl:input >
				<soap:body use="literal" />
			</wsdl:input>
			<wsdl:output >
				<soap:body use="literal" />
			</wsdl:output>
			<wsdl:fault name="simpleOperationFault">
				<soap:fault name="simpleOperationFault" use="literal" />
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="simpleWebService">
		<wsdl:port binding="simpleWebService:simpleServiceSOAP"
			name="simpleServiceSOAP">
			<soap:address
				location="http://www.nicolas.com.ar/simpleWebService" />
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
